# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read

jobs:
  semantic-commit-linter:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install semantic-release
        run: |
          npm install semantic-release -D
          npm install @semantic-release/commit-analyzer -D
      - name: Run Semantic Commit Analyzer
        run: npx semantic-release/commit-analyzer

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: semantic-commit-linter
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Check formatting & Run Tests
        run: sbt fmtCheck testAll
        # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: run-tests
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install semantic-release
        run: |
          npm install semantic-release -D
          npm install @semantic-release/commit-analyzer -D 
          npm install @semantic-release/release-notes-generator -D
          npm install @semantic-release/changelog 
          npm install @semantic-release/exec -D
          npm install @semantic-release/git -D
          npm install @semantic-release/github -D
          npm install conventional-changelog-conventionalcommits -D
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}