name: Semantic Release

on:
  workflow_run:
    workflows: ['Semantic Commit Linter']
    types: [completed]
    branches:
      - 'main'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  semantic-release:
    name: Semantic Release
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install semantic-release
        run: |
          npm install semantic-release -D
          npm install @semantic-release/commit-analyzer -D 
          npm install @semantic-release/release-notes-generator -D
          npm install @semantic-release/changelog 
          npm install @semantic-release/exec -D
          npm install @semantic-release/git -D
          npm install @semantic-release/github -D
          npm install conventional-changelog-conventionalcommits -D
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}